name: Build

on:
  push:
    branches:
      - sonar

jobs:
  sonarcloud:
    name: SonarCloud
    #runs-on: self-hosted
    runs-on: ubuntu:latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKON: ${{ secrets.GITHUB_SONAR_TOKEN }} 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
